# -*- coding: utf-8 -*-
"""citationPipeline_RR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWeOuXiCVBeAU_NWjvk7EhVhhUu8ahsa
"""

# import the requests package and set your token in a variable for later use
import requests

token="GlBIHOAHes7BPcdGqyanZKAuwXcmNVziwDlBdJgK"

from urllib.parse import urlencode, quote_plus

# get the metadata from the sci-X api. This query obtains the title, bibcode,
# doi, citation list, and citation count for all datasets that have a DOI, up to 100.
# query is rate limited to return up to 2000 results regardless of the "rows" value

# accented letters, special characters, and spaces need to be encoded
rows = 100
encoded_query = urlencode({"q": 'doctype:dataset doi:"1*"',
                           "fl": "title, bibcode, doi, citation_count, citation",
                           "rows": rows
                          })
encoded_query = urlencode(query)
print(encoded_query)
# note that the colon (:) may be encoded, depending on the algorithm you use. Your request
# should accept either the unencoded colon (:) or the encoded version (%3A)

search_results = requests.get("https://api.adsabs.harvard.edu/v1/search/query?{}".format(encoded_query), \
                       headers={'Authorization': 'Bearer ' + token})
print('Execution successful.')

# number of datasets with DOIs returned
# should match row value in previous block

len(search_results.json()["response"]["docs"])

# filter out all datasets that have a citation_count=0

cited_list = [search_results.json()["response"]["docs"][i] for i in
              range(len(search_results.json()["response"]["docs"])) if
              search_results.json()["response"]["docs"][i]["citation_count"] > 0]
print(len(cited_list))
cited_list[0]

# the query can only be run for one bibcode at a time, looping here
# loop through all returned datasets with DOIs

bibcode_doi_cache, missing_DOI_cnt = {}, 0
for idx in range(len(cited_list)):
  bibcode_list, doi_list = cited_list[idx]['citation'], []
  for i in range(len(bibcode_list)):

    # save compute time by pulling dois from the cache
    if bibcode_list[i] in list(bibcode_doi_cache.keys()):
      doi_list.append(bibcode_doi_cache[bibcode_list[i]])
      if bibcode_doi_cache[bibcode_list[i]] is None:
        missing_DOI_cnt += 1
      print("DOI found in cache for bibcode "+str(bibcode_list[i]))
      continue

    # run the query for the bibcode
    encoded_query = urlencode({"q": "bibcode:"+str(bibcode_list[i]),
                                "fl": "doi, id", "rows": 1})
    results = requests.get("https://api.adsabs.harvard.edu/v1/search/query?{}".format(encoded_query), \
                          headers={'Authorization': 'Bearer ' + token})
    # print('Execution successful.')
    # print(results.json()['response']['docs'])

    # sanity check: only one record should be returned. Should investigate otherwise.
    # if no DOI found, skip to next bibcode
    if len(results.json()['response']['docs']) > 1:
      print("Warning: more than one record returned for bibcode "+str(bibcode_list[i]))
    elif 'doi' not in list(results.json()['response']['docs'][0]):
      #print("Warning: no DOI found for bibcode "+str(bibcode_list[i]))
      bibcode_doi_cache[bibcode_list[i]] = None
      missing_DOI_cnt += 1
      continue

    # remove arXiv DOIs from the list
    doi = [results.json()['response']['docs'][0]['doi'][i] for i in
          range(len(results.json()['response']['docs'][0]['doi'])) if 'arXiv'
          not in results.json()['response']['docs'][0]['doi'][i]]
    # print(doi)

    # sanity check: should only have one DOI per publication after filtering. Print bibcode otherwise
    # if no DOI found, skip to next bibcode
    if len(doi) > 1:
      print("Warning: More than one DOI found for: "+bibcode_list[i])
    elif len(doi) == 0:
      # print(f"No non-arXiv DOI found for bibcode {bibcode_list[i]}")
      bibcode_doi_cache[bibcode_list[i]] = None
      missing_DOI_cnt += 1
      continue
    else:
      doi_list.extend(doi)
      bibcode_doi_cache[bibcode_list[i]] = doi

  cited_list[idx]['citation_doi'] = doi_list

  # sanity check
  try:
    assert len(cited_list[idx]['citation']) - len(cited_list[idx]['citation_doi']) == missing_DOI_cnt, \
      f"Number of bibcodes with missing DOIs doesn't match. Should be : {missing_DOI_cnt}" + \
      f"Actual: {len(cited_list[idx]['citation']) - len(cited_list[idx]['citation_doi'])}"
  except AssertionError as e:
    print(e)

import json

with open('cited_list'+str(rows)+'.json', 'w') as f:
    json.dump(cited_list, f, indent=4)

