# -*- coding: utf-8 -*-
"""cited_list10_0_MassExtractions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pEU7tL9hIXck-9yxZ6ZRBKMcTmnNcZS
"""

import requests

url = 'https://raw.githubusercontent.com/Ruizia-LSC/adsabs-dev-api/master/cited_list10_0.json'
file_name = 'cited_list10_0.json'

try:
    response = requests.get(url)
    response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
    with open(file_name, 'wb') as f:
        f.write(response.content)
    print(f"Successfully downloaded '{file_name}' from GitHub.")
except requests.exceptions.RequestException as e:
    print(f"Error downloading '{file_name}': {e}")

#Step 1
import json

# Load the cited_list10_0.json file
with open("cited_list10_0.json", "r", encoding="utf-8") as f:
    cited_data = json.load(f)

doi_list = []
for record in cited_data:
    dois = record.get("doi", [])
    if dois:
        doi_list.extend(dois)

print("Extracted DOIs:")
for i, doi in enumerate(doi_list):
    print(f"{i + 1}. {doi}")
#Step2
import json
import requests
from typing import Any, Dict, List

DATACITE_API = "https://api.datacite.org/dois"

def _safe_get(dct: Dict[str, Any], *keys, default=None):
    cur = dct
    for k in keys:
        if not isinstance(cur, dict):
            return default
        cur = cur.get(k)
    return cur if cur is not None else default


def _normalize_record(item: Dict[str, Any]) -> Dict[str, Any]:
    attrs = item.get("attributes", {}) or {}

    creators = []
    for c in attrs.get("creators", []) or []:
        name = c.get("name")
        if not name:
            given = c.get("givenName", "") or ""
            family = c.get("familyName", "") or ""
            name = f"{given} {family}".strip() or None
        if name:
            creators.append(name)

    titles = [t.get("title") for t in (attrs.get("titles", []) or []) if t.get("title")]
    subjects = [s.get("subject") for s in (attrs.get("subjects", []) or []) if s.get("subject")]
    descriptions = [d.get("description") for d in (attrs.get("descriptions", []) or []) if d.get("description")]
    rights = [r.get("rights") for r in (attrs.get("rightsList", []) or []) if r.get("rights")]

    return {
        "id": item.get("id"),
        "doi": attrs.get("doi"),
        "titles": titles,
        "creators": creators,
        "publisher": attrs.get("publisher"),
        "publication_year": attrs.get("publicationYear"),
        "resource_type_general": _safe_get(attrs, "types", "resourceTypeGeneral"),
        "url": attrs.get("url"),
        "published": attrs.get("published"),
        "updated": attrs.get("updated"),
        "registered": attrs.get("registered"),
        "language": attrs.get("language"),
        "rights": rights,
        "version": attrs.get("version"),
    }


def _metadata_diff(old: Dict[str, Any], new: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    """
    Compare two normalized versions and return only changed fields.
    """
    tracked_fields = [
        "doi",
        "titles",
        "creators",
        "publisher",
        "publication_year",
        "resource_type_general",
        "url",
        "language",
        "rights",
        "version",
        "state",
    ]

    changes = {}
    for field in tracked_fields:
        if old.get(field) != new.get(field):
            changes[field] = {"old": old.get(field), "new": new.get(field)}
    return changes


def fetch_datacite_metadata_with_history(
    doi: str,
    timeout: int = 20,
    page_size: int = 100,
) -> Dict[str, Any]:
    """
    Fetch DataCite metadata for DOI and include all available versions/iterations.
    """
    if not doi or not doi.strip():
        raise ValueError("DOI must be a non-empty string.")

    doi = doi.strip()

    resp = requests.get(
        DATACITE_API,
        params={"query": doi, "page[size]": page_size},
        timeout=timeout,
    )
    resp.raise_for_status()
    payload = resp.json()

    items = payload.get("data", []) or []
    if not items:
        raise ValueError(f"No DataCite records found for DOI query: {doi}")

    chosen = None
    doi_lower = doi.lower()
    for item in items:
        item_doi = (_safe_get(item, "attributes", "doi", default="") or "").lower()
        if item_doi == doi_lower:
            chosen = item
            break
    if chosen is None:
        chosen = items[0]

    current = _normalize_record(chosen)
    canonical_doi = current.get("doi") or doi

    versions_url = f"{DATACITE_API}/{canonical_doi}/versions"
    v_resp = requests.get(
        versions_url,
        params={"page[size]": page_size},
        timeout=timeout,
    )

    history: List[Dict[str, Any]] = []
    if v_resp.status_code == 200:
        v_payload = v_resp.json()
        v_items = v_payload.get("data", []) or []
        history = [_normalize_record(v) for v in v_items]
    else:
        history = [current]

    current_id = current.get("id")
    if current_id and all(h.get("id") != current_id for h in history):
        history.append(current)

    def _sort_key(rec: Dict[str, Any]):
        return (
            rec.get("registered") or "",
            rec.get("published") or "",
            rec.get("updated") or "",
            rec.get("id") or "",
        )

    history = sorted(history, key=_sort_key)

    changes_between_versions = []
    for i in range(1, len(history)):
        old = history[i - 1]
        new = history[i]
        changes = _metadata_diff(old, new)
        if changes:
            changes_between_versions.append(
                {
                    "from_index": i - 1,
                    "to_index": i,
                    "from_id": old.get("id"),
                    "to_id": new.get("id"),
                    "changes": changes,
                }
            )

    return {
        "query_doi": doi,
        "canonical_doi": canonical_doi,
        "current": current,
        "history": history,
        "changes_between_versions": changes_between_versions,
    }
#Step3
import json
import time

# Ensure doi_list and fetch_datacite_metadata_with_history are available
if 'doi_list' in locals() and 'fetch_datacite_metadata_with_history' in globals():
    processed_count = 0
    failed_dois = []

    for i, current_doi in enumerate(doi_list):
        print(f"\nProcessing DOI {i + 1}/{len(doi_list)}: {current_doi}")
        try:
            # Fetch metadata for the current DOI
            datacite_result_all = fetch_datacite_metadata_with_history(current_doi)

            # Create a valid filename from the DOI
            filename = f"{current_doi.replace('/', '_')}_DataciteResult.JSON"

            # Save the datacite_result to the JSON file
            with open(filename, 'w', encoding='utf-8') as f:
                json.dump(datacite_result_all, f, ensure_ascii=False, indent=2)

            print(f"Successfully saved metadata for {current_doi} to {filename}")
            processed_count += 1

        except Exception as e:
            print(f"Failed to fetch or save metadata for {current_doi}: {e}")
            failed_dois.append(current_doi)

        # Add a small delay to avoid hitting API rate limits, if applicable
        time.sleep(0.5)

    print(f"\nFinished processing. Total DOIs processed: {processed_count}/{len(doi_list)}")
    if failed_dois:
        print("DOIs that failed to process:")
        for failed_doi in failed_dois:
            print(f"- {failed_doi}")
else:
    print("Error: 'doi_list' or 'fetch_datacite_metadata_with_history' not found. Please ensure preceding cells were executed.")

import json

# Load source data from cited_list10_0.json
with open('cited_list10_0.json', 'r') as f:
    cited_data = json.load(f)

citation_doi_list = []

for entry in cited_data:
    # Get the parent DOI. It appears to be a list, so take the first element if available.
    parent_doi_list = entry.get('doi')
    parent_doi = parent_doi_list[0] if parent_doi_list else None

    # Get the list of citation DOIs directly from the entry.
    entry_citation_dois = entry.get('citation_doi', [])

    if parent_doi:  # Only proceed if a parent DOI exists
        for citation_doi in entry_citation_dois:
            if citation_doi:  # Ensure the citation_doi is not None or empty
                citation_doi_list.append({
                    'parent_doi': parent_doi,
                    'citation_doi': citation_doi
                })

# Display the resulting list
print(f"Found {len(citation_doi_list)} citation DOIs.\n")
# Pretty print all items for better readability
print(json.dumps(citation_doi_list, indent=2))

# You can also display the full list if needed, or save it to a DataFrame

# Step 2
import time
import os # Import the os module to handle file paths and directory creation

def fetch_and_save_crossref_metadata(doi, email_for_polite_pool=None, output_folder='.'):
    """Fetches Crossref metadata for a given DOI and saves it to a JSON file in the specified output folder."""
    crossref_url = f"https://api.crossref.org/works/{doi}"
    # Add a 'mailto' parameter for polite pool usage if an email is provided
    headers = {"User-Agent": f"CitationMetadataFetcher/1.0 (mailto:{email_for_polite_pool})"} if email_for_polite_pool else {}

    # Replace '/' with '_' in the DOI to create a valid filename
    file_name = f"{doi.replace('/', '_')}_CrossrefCall.json"
    file_path = os.path.join(output_folder, file_name)

    try:
        print(f"Fetching metadata for DOI: {doi}")
        response = requests.get(crossref_url, headers=headers)
        response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
        crossref_data = response.json()

        # Add the queried URL and original DOI to the metadata
        crossref_data['queried_url'] = crossref_url
        crossref_data['original_doi'] = doi

        with open(file_path, 'w') as f:
            json.dump(crossref_data, f, indent=2)
        print(f"Successfully saved metadata for {doi} to {file_path}")
        return crossref_data
    except requests.exceptions.RequestException as e:
        print(f"Error fetching or saving metadata for DOI {doi}: {e}")
        return None

#Step 3
import time
import os # Import the os module to handle file paths and directory creation

# You can optionally provide an email for the Crossref polite pool. Replace 'your-email@example.com' with your actual email.
# This is recommended by Crossref to avoid being blocked if you make many requests.
# user_email = "your-email@example.com" # Uncomment and replace with your email if desired
user_email = None # Or keep None if you don't want to provide an email

# Define the base output folder name
base_output_folder_name = 'DOI_Crossref_Calls_by_ParentDOI'

# Create the base output folder if it doesn't exist
if not os.path.exists(base_output_folder_name):
    os.makedirs(base_output_folder_name)
    print(f"Created base directory: {base_output_folder_name}")

# List to store all fetched metadata (optional, depends on further needs)
all_crossref_metadata = []

print(f"Starting to process {len(citation_doi_list)} citation DOIs...")
for i, entry in enumerate(citation_doi_list):
    citation_doi = entry['citation_doi']
    parent_doi = entry['parent_doi']

    # Sanitize parent_doi to create a valid folder name
    sanitized_parent_doi = parent_doi.replace('/', '_').replace(':', '_')
    specific_output_folder = os.path.join(base_output_folder_name, sanitized_parent_doi)

    # Create the specific parent_doi subfolder if it doesn't exist
    if not os.path.exists(specific_output_folder):
        os.makedirs(specific_output_folder)
        print(f"Created sub-directory for parent DOI '{parent_doi}': {specific_output_folder}")

    metadata = fetch_and_save_crossref_metadata(citation_doi, user_email, output_folder=specific_output_folder)
    if metadata:
        all_crossref_metadata.append({
            'parent_doi': parent_doi,
            'citation_doi': citation_doi,
            'crossref_metadata': metadata
        })
    # Add a delay to respect Crossref API rate limits (e.g., 0.5 seconds per request)
    # This helps avoid overwhelming the API and getting blocked.
    time.sleep(0.5)
    if (i + 1) % 50 == 0: # Print a progress update every 50 DOIs
        print(f"Processed {i + 1}/{len(citation_doi_list)} DOIs.")

print(f"\nFinished processing {len(citation_doi_list)} citation DOIs. Metadata for successful requests saved as individual JSON files in subfolders within the '{base_output_folder_name}' directory.")
print(f"Total metadata items successfully fetched and stored in 'all_crossref_metadata' list: {len(all_crossref_metadata)}")

"""
Results.py
---------
Runs checks for ONE DataciteResult JSON file against every individual
Crossref-call JSON file found in the corresponding sibling Crossref folder.
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_json(path: Path) -> Optional[Any]:
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return None

def json_contains_string(obj: Any, needle: str) -> bool:
    needle_lower = needle.lower()
    if isinstance(obj, str):
        return needle_lower in obj.lower()
    if isinstance(obj, dict):
        return any(json_contains_string(v, needle) for v in obj.values())
    if isinstance(obj, list):
        return any(json_contains_string(item, needle) for item in obj)
    return False

def _normalize_container(value: Any) -> str:
    if isinstance(value, dict):
        return json.dumps(value, sort_keys=True, ensure_ascii=False, indent=2)
    return str(value)

def find_container(obj: Any, needle: str) -> Optional[Any]:
    needle_lower = needle.lower()
    def _walk(node: Any, parent: Optional[Any]) -> Optional[Any]:
        if isinstance(node, str):
            return parent if needle_lower in node.lower() else None
        if isinstance(node, dict):
            for v in node.values():
                found = _walk(v, node)
                if found is not None: return found
        if isinstance(node, list):
            for item in node:
                found = _walk(item, node)
                if found is not None: return found
        return None
    return _walk(obj, None)

def check_previous_title(history: List[Dict[str, Any]]) -> bool:
    if len(history) < 2: return False
    first_titles = set(history[0].get("titles", []))
    for entry in history[1:]:
        if set(entry.get("titles", [])) != first_titles: return True
    return False

def check_container_found(crossref_data: Any, doi: str, titles: List[str], d_found: bool, t_found: bool) -> Any:
    if not doi or not titles or (not d_found and not t_found): return "null"
    containers = []
    seen = set()
    if d_found:
        c = find_container(crossref_data, doi)
        if c is not None:
            n = _normalize_container(c)
            if n not in seen: seen.add(n); containers.append(c)
    if t_found:
        for t in titles:
            if t and json_contains_string(crossref_data, t):
                c = find_container(crossref_data, t)
                if c is not None:
                    n = _normalize_container(c)
                    if n not in seen: seen.add(n); containers.append(c)
                break
    return containers[0] if len(containers) == 1 else (containers if containers else "null")

def process_datacite_file(datacite_path: Path, crossref_files: List[Path]) -> Dict[str, Any]:
    dc_data = load_json(datacite_path)
    if not dc_data: return {"error": "Load error"}
    doi = dc_data.get("canonical_doi", "")
    titles = dc_data.get("current", {}).get("titles", [])
    prev_title = check_previous_title(dc_data.get("history", []))
    results = []
    for cf in sorted(crossref_files):
        cr = load_json(cf)
        if not cr: continue
        d_hit = json_contains_string(cr, doi)
        t_hit = any(json_contains_string(cr, t) for t in titles if t)
        results.append({
            "Publication DOI": cr.get("original_doi", cf.stem.replace('_', '/')),
            "DOITest": d_hit,
            "TitleTest": t_hit,
            "PreviousTitle": prev_title,
            "ContainerFound": check_container_found(cr, doi, titles, d_hit, t_hit)
        })
    return {"datasetDOI": doi, "datasetTitle": titles, "results": results}

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-dir", default=".")
    args, _ = parser.parse_known_args(args=[] if 'google.colab' in sys.modules else None)

    base_dir = Path(args.base_dir).resolve()
    output_dir = base_dir / "CrossCheckResults"
    output_dir.mkdir(exist_ok=True)

    dois = globals().get('doi_list', [])
    for doi in dois:
        safe = doi.replace('/', '_')
        dc_file = base_dir / f"{safe}_DataciteResult.JSON"
        cr_dir = base_dir / "DOI_Crossref_Calls_by_ParentDOI" / safe
        if dc_file.exists() and cr_dir.exists():
            print(f"Processing: {doi}")
            files = list(cr_dir.glob("*.json"))
            out = process_datacite_file(dc_file, files)
            with open(output_dir / f"{safe}_CrossCheckResult.json", "w") as f:
                json.dump(out, f, indent=2)
    print(f"\nDone. Results in {output_dir}")

if __name__ == "__main__":
    main()

import shutil
from google.colab import files

# Define the folder to download and the output zip name
folder_to_zip = 'CrossCheckResults'
output_zip = 'CrossCheckResults.zip'

# Compress the folder into a zip file
shutil.make_archive('CrossCheckResults', 'zip', folder_to_zip)

# Trigger the download to your local machine
files.download(output_zip)

print(f"Successfully zipped '{folder_to_zip}' into '{output_zip}' and initiated download.")